version: '2'

tasks:
  deps:
    desc: Build go repos
    cmds:
      - bazel run //:gazelle update-repos -- -from_file=go.mod

  build:
    desc: Build the codebase
    cmds:
      - bazel build //:bosun --verbose_failures
